### ISSUE TITLE
Dashboard: read only on the editor

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#114]
Hello 👋,

### 👀 Background 

The RestQA Dashboard could be deployed on a remote server. However some team would like to deploy the server in order to access to all the feature and run any of them.

### ✌️ What is the actual behavior? 

Each feature file could be updated by anyone through the dashboard UI.

### 🕵️‍♀️ How to reproduce the current behavior? 

1. Install RestQA
2. Run the command `restqa init` to initialize a brand new project
3. Run the command `restqa dashboard` to launch the dashboard
4. Access the dashboard through the url http://localhost:8081
5. Go to Editor menu and update one feature file.

###   🤞 What is the expected behavior?

On some team setup we would prefer to not allow the user to edit the the feature when the restqa dashboard is deployed on a remote server. 

###   😎 Proposed solution.

On the `.restqa.yml` configuration file , we could add the property `editable` is the object `restqa.dashboard` such as :

```yaml
restqa:
  dashboard:
    editable: true
```

The default value will be true.

The value could also be overrode by the environment variable `RESTQA_DASHBOARD_EDITABLE=true`, example: 
```
RESTQA_DASHBOARD_EDITABLE=false restqa dashboard
```

Or through the  option `-e | --editable`

```
restqa dashboard --editable false
```

Cheers.

**Comment by tony-go** [comment]
Hi @olivierodo 

As you see, I pushed few lines on the PR #120. From the feature POV, it just misses to handle the `--editable` arg.

But, it remains a question mark on my side: regarding the environment variables. As we have a configuration file, Which one is the real source of truth ?

I mean what's happen if the dashboard environement variables say "editable" and config files say "not editable" ? 

If we want to move forward quickly, we can open a specific issue for that continue to work on the feature without this "env var" aspect. 

Let me know.

**Comment by tony-go** [comment]
Owww maybe the env variable you mention is the one that will be used by the CLI to generate the `restqa` config file ?

**Comment by olivierodo** [comment]
No actually from a team context perspective we could face the following pattern:

1. Dev team run the dashboard on local so the flag  of `restqa.dashboard.editable` will be set to true.
2. Dev team are committing the config file as-is.
3. The continuous integration pipeline will deploy the updated dashboard into a server
4. However the dashboard hosted on the server  should not be editable
5. Then we could imagine when the devops configure restqa on the server he could use: `RESTQA_DASHBOARD_EDITABLE=false restqa dashboard` in order to override the configuration set from the `.restqa.yml`

Is the context helping you more to understand this specific part ?

**Comment by olivierodo** [comment]
In order to enhance the user experience and the reuse common terms I think we should switch the term `editable` by `read-only`.

1. In the configuration file:

```
restqa:
  dashboard:
    read-only: true
```

2. Environement variable

```
RESTQA_DASHBOARD_READONLY=true  restqa dashboard
```
3. Command line options

```
restqa dashboard --read-only
```
