### ISSUE TITLE
[DASHBOARD] Track source of  traffic for the sponsors

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#132]
Hello 👋,

### 👀 Background 

Sponsors have their logo displayed on the dashboard, however there is no way for the sponsor to know that someone access to their website from the RestQA dashboard

### ✌️ What is the actual behavior? 

On the RestQA Dashboard main page when the user is clicking on the logo he is redirected to the sponsor website.

### 🕵️‍♀️ How to reproduce the current behavior? 

* Clone the repository
* Install the dependencies : `npm i`
* Install the dependencies of the dashboard: `npm run dashboard:install`
* Run the dashboard on dev mode: `npm run dashboard:dev`
* Access to the dashboard from your browser http://localhost:8081
* Click on one for the sponsor logo.

###   🤞 What is the expected behavior?

When we click on the sponsor logo we should be redirected to the sponsor website, the sponsor should be able to know the source of the traffic

![image](https://user-images.githubusercontent.com/4768226/132320396-c53dc1b3-8e39-422f-b952-e64881c58b9c.png)

###   😎 Proposed solution.

- [ ] Add utm information on the sponsor url: `https://example.com?utm_source=dashboard&utm_medium=referral&utm_campaign=restqa`

Cheers.

**Comment by masonwoodford** [comment]
npm run dashboard:install seems to be failing on my end. :sneezing_face:
