### ISSUE TITLE
🐞 [Bug]: Impossible to use report on Firefox

### ISSUE THREAD

**Issue by tony-go** [restqa/restqa#243]
### Contact Details

gorez.tony@gmail.com

### What happened?

When I tried to run RestQA with the `--report` flag, it opened the `file://...` link in my browser, and the page stuck with the spin loader never stopped.

### Relevant log output

```shell
I got this error: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Too_much_recursion
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Hack that needs to be applied due to a the missing hash on the runtime
Ref: https://github.com/vitejs/vite/blob/8ea71b44530af4a23d2c635e6e380d97a84c8919/packages/vite/src/client/client.ts#L589
