### ISSUE TITLE
🐞 [Bug]: Report UI -Incorrect  RestQA version on the footer

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#287]
### What happened?

While generating the report, we should display the current RestQA version however on the footer currently the version displayed is: 0.0.0-generated.
It should be the actual version.

![image](https://user-images.githubusercontent.com/4768226/205789877-5d1900e0-2de0-4762-bb06-c163b37c9f94.png)

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tony-go** [comment]
A few entry points:

- The UI: https://github.com/restqa/restqa/blob/master/packages/report-ui/src/layouts/partials/Footer.vue#L15
- Where does the data come from: https://github.com/restqa/restqa/blob/master/packages/report-ui/src/layouts/partials/Footer.vue#L25-L27

But in fact, I think that the store does not contain this info:
- https://github.com/restqa/restqa/blob/master/packages/report-ui/src/store/modules/restqa/getters.js
- https://github.com/restqa/restqa/blob/master/packages/report-ui/src/store/modules/restqa/state.js

**Comment by tony-go** [comment]
The strategy could be:
- add a version property in the store (`store/modules/restqa/state`)
- add a getter (`store/modules/restqa/getters`)
- use the proper getter in `Footer.vue`

**Comment by olivierodo** [comment]
I believe the issue is coming from 
https://github.com/restqa/restqa/blob/master/packages/cli/src/formatters/export-formatter.js#L129

The fact that we import the `package.json` this way: https://github.com/restqa/restqa/blob/master/packages/cli/src/formatters/export-formatter.js#L2

It means that during the build we are embedding the current package.json that has a placeholder version that will be replaced during the publication of the package (https://github.com/restqa/restqa/blob/master/.github/workflows/publish.yml#L19)

So the solution should be to have a function that will load and read the package.json on at the runtime. 😅
