### ISSUE TITLE
🚀 [FEATURE]: Enable contribution panel by default

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqa#354]
### 👀 Background

RestQA has the ability to share the current contribution status of your project
Example:
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/4768226/226154049-bd7fe214-b0e5-4827-922e-c45392ede3e1.png">

### ✌️ What is the actual behavior?

Current the panel is only available if RestQA detect that the project is using Git.
The detection logic is just checking if the project contains a `.git` folder

### 🕵️‍♀️ How to reproduce the current behavior?

1. Install RestQA
2. add a `.git` folder in your project
3. run the command `restqa run --report`
4. remove the `.git`folder 
5. run the command `restqa run --report`
6. The contribution panel is not displayed

### 🤞 What is the expected behavior?

Actually in a case of mono repo, RestQA might not be run at the root level, then it mean thje folder `.git` will not be present....
We should look at enabling the contribution panel regardless of the presence of the `.git folder`

### 😎 Proposed solution.

Let's remove the condition of checking the `.git` folder

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developerHet** [comment]
I would like to work on this issue :)

**Comment by developerHet** [comment]
can I make changes to UI? if there are no contributors then I render messages related to that as shown in the image.
![image](https://user-images.githubusercontent.com/79783828/226433207-93b4703a-c941-4bc5-afdd-ef863ed66650.png)

**Comment by olivierodo** [comment]
Yes that a great idea :)
Related to the text, can you put something like:
So far we could identify the list of code contributor  🤨, Are you using Git?

**Comment by developerHet** [comment]
ok working on it :)

**Comment by developerHet** [comment]
done :) if want any changes than feel free to tell.
