### ISSUE TITLE
🚀 [FEATURE]: Add some text status to the Rhino

### ISSUE THREAD

**Issue by rezaalmanda** [restqa/restqa#365]
### 👀 Background

As an engineer/user I like to know the current result of my newer test scenario

### ✌️ What is the actual behavior?

Currently there are images that shown how the result was Passed or Not, but with no explanation text like this one. People might be wondering what was that about ![image](https://user-images.githubusercontent.com/22217419/227068641-98b4549a-1dd1-46a8-84bc-32ed5ec8abe7.png)

### 🤞 What is the expected behavior?

It should be much more better by providing explanation text on the images, so people can figure out what's happening with the current test scenarion they're tested.

### 😎 Proposed solution.

Here my solution, provide a text to the rhino images that tell test case that you run is "PASSED" and "FAILED" like the example below.
![New dashboard](https://user-images.githubusercontent.com/22217419/227069445-bfb01f87-3c9e-4ceb-abf5-ad49c78c8297.png)

![Failed test case](https://user-images.githubusercontent.com/22217419/227399110-3a2ec074-dc97-42ce-9b0a-93b3633d8bcf.png)

You can use this image for Passed test case:
![drawing new](https://user-images.githubusercontent.com/22217419/227072849-4345bfe4-bf38-4226-b6ce-86976c0e67c4.png)

and this image for Failed test case :
![Failed](https://user-images.githubusercontent.com/22217419/227397952-e0b6b39f-3c3b-4925-8ded-4304e3e9d6af.png)

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developerHet** [comment]
@rezaalmanda @olivierodo anyone can help me? please can you elaborate on current behavior and expected behavior?

**Comment by olivierodo** [comment]
Hi @developerHet ,
Actually that simple image replacement.
currently as you can see the rhino on top that expressing happiness because the Test succedd look like:

![image](https://user-images.githubusercontent.com/4768226/227182369-d42aca80-1814-4b1c-9566-2ff75684834a.png)

However we would like to have an extra text showing that the rhino is saying "It passed"

**Comment by rezaalmanda** [comment]
I just updated my feature request @olivierodo, so yeah @olivierodo was right that we need an image replacement for the rhinos, @developerHet. that tell when test case that you run with restQA is "Passed" means no error whatsoever and "Failed" means it contains some error in your test case. So you need to create two example test case in restqa in order this feature come to live.

**Comment by rezaalmanda** [comment]
I just updated my feature request @olivierodo, so yeah @olivierodo was right that we need an image replacement for the rhinos, @developerHet. that tell when test case that you run with restQA is "Passed" means no error whatsoever and "Failed" means it contains some error in your test case. So you need to create two example test case in restqa in order this feature come to live.

**Comment by rezaalmanda** [comment]
Let me know if you still have question or my answer not clear enough.

**Comment by developerHet** [comment]
@rezaalmanda @olivierodo I used my own images to add this feature because the given image size is not matched already existing images also I didn't change the face direction of the rhino for a failed case.
Thank you :)

**Comment by rezaalmanda** [comment]
> @rezaalmanda @olivierodo I used my own images to add this feature because the given image size is not matched already existing images also I didn't change the face direction of the rhino for a failed case. Thank you :)

That's okay, Thank you btw :D
