### ISSUE TITLE
🐞 [Bug]: Search Bar Design Is Broken

### ISSUE THREAD

**Issue by developerHet** [restqa/restqa#366]
### Contact Details

hetpatel2312.hp@gmail.com

### What happened?

I found in the Documentation section bottom right side search field design is broken.
Image:
![image](https://user-images.githubusercontent.com/79783828/227183089-64f7ebac-d47c-4369-90a1-fd3f3e1fcfcb.png)

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by developerHet** [comment]
I would like to work on it :)

**Comment by olivierodo** [comment]
Sure, Actually this morning we were talking with @rezaalmanda  a little bit of some future UX enhancement.
But your contribution is definitely welcomed 🙏.
