### ISSUE TITLE
🚀 [FEATURE]: Change the position of Search bar in the Documentation Page

### ISSUE THREAD

**Issue by rezaalmanda** [restqa/restqa#378]
### 👀 Background

The current search bar/box in the documentation page is small and and quite hard to find/notice (i think), and the wording may sound off a little bit. This may lead to potential user or even current user that use RestQA feel annoyed, because they can't navigate the documentation page easily with help the search bar

### ✌️ What is the actual behavior?

As you can see below, the search bar/box located at the right below side on your screen, crumpled and small
![image](https://user-images.githubusercontent.com/22217419/233974102-86f27fd7-6de4-46e0-a58c-66548c9c68a3.png)

### 🤞 What is the expected behavior?

 So I proposed to redesign the search bar/box in the documentation page, make it stand out and little bigger. It may helps people use the function and solve problems faster

### 😎 Proposed solution.

Like this one
![Search Bar Proposed](https://user-images.githubusercontent.com/22217419/233978340-f8811b9d-171d-488e-a8cd-9c64019c7386.png)

### 🙏 Would you be willing to submit a PR?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Love it! 🫶

**Comment by olivierodo** [comment]
@developerHet Interested by this challenge ?

**Comment by Donbasilpeter** [comment]
hello I have added a PR regarding the issue. #379 
please review it and give a feedback

**Comment by rezaalmanda** [comment]
The search bar specification is 530 width, 40 height and also make it centered.

**Comment by olivierodo** [comment]
Done 😄 

![image](https://github.com/restqa/restqa/assets/4768226/6140179b-e3c6-43f4-b35c-f96e7d96e78d)
