### ISSUE TITLE
🚀 [FEATURE]: Add language support (aka translation) for RestQA

### ISSUE THREAD

**Issue by rezaalmanda** [restqa/restqa#380]
### 👀 Background

I'm thinking that it would be helpful if we add translation to another language for RestQA, it will help attract more people to the project, some of them may able to contribute and use the software for their own project. It is good for RestQA as well for the long term. At first we can translate the Documentation Page into another language, let's say french, german, indian or so.

### ✌️ What is the actual behavior?

Currently we only use 1 language, english-only. But looking at how diverse our community had in Discord and Github, it is an good idea to add support for other languages

### 🤞 What is the expected behavior?

Have several language support

### 😎 Proposed solution.

I proposed that we use https://weblate.org/en/ for the translation work, since they have free tier for open-source/libre software that we can request to them for RestQA

### 🙏 Would you be willing to submit a PR?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Thank you @rezaalmanda, I believe the first step for us will be to extract all text into one single file.
As of now the console message are already centralized into: https://github.com/restqa/restqa/blob/master/packages/core-logger/locales/en.json

Only the text from the Dashboard remains to do.

**Comment by olivierodo** [comment]
Then I believe the biggest challenge will be on the documentation (50+ pages). However as proposed by @KaTLaz we might just prioritize first the pages for the onboarding such as: [Getting started](https://github.com/restqa/restqa/blob/master/docs/getting-started/_index.md).
