### ISSUE TITLE
🚀 [FEATURE]: Redesign History section on the dashboard

### ISSUE THREAD

**Issue by rezaalmanda** [restqa/restqa#381]
### 👀 Background

Currently we have simple history page but no so intuitive in the terms giving information to QAs/User, it only show test id, color coded of the status from the test and date that you run the test. and I think we need to change that at least how to make this history section more usable and informative.

![Dashboard](https://github.com/restqa/restqa/assets/22217419/76f58896-15f2-4932-8ee0-0250323b04b7)

### ✌️ What is the actual behavior?

 The current behavior that the history section only show that information and we're unable to click the detail and don't know how to find that test id in the system, it just shown as is every time you finish the test.

### 🤞 What is the expected behavior?

How might we better track of test that we run?
How might we able to see our overall code performance?
How might we able to show the summarize to the QAs/User with timely based?

### 😎 Proposed solution.

This is my proposed solution as is for now, I'm open for discussion
This is my first design for the history section, I created a graph with color coded block, Green (passed), red (error) and how many test have you been doing in that day. User also can filter how the test going by clicking dropdown button on the top right hand side, by daily, weekly, monthly or so.
![History page](https://github.com/restqa/restqa/assets/22217419/8a8b4d1b-8136-482a-acc8-e0b87a166c2e)

This one i show an hover when you want to see the detail of each block, it only show how many test that are passed, error block will do similary.
![History page 2](https://github.com/restqa/restqa/assets/22217419/8b48dd5c-4704-43ed-8ead-839d79ba35eb)

By this I was hoping user can utilize the history section more as well helping them better track how the test of their code going, It also can add an capability to see does the code improve (less error) each month/year

### 🙏 Would you be willing to submit a PR?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivierodo** [comment]
Thank You @rezaalmanda, that a great enhancement, actually what do you think of having a bar stack chart
Example:
<img width="508" alt="image" src="https://github.com/restqa/restqa/assets/4768226/c235e2df-7c6f-4dd4-b981-48f88e7bfc68">

I think it will help better when the history will have multiple items.

What do you think?

**Comment by rezaalmanda** [comment]
hmm, I think this is also good idea because we can save some space by stacking it, and those text "Cherry St" etc can be use as date. So we can have 5-7 days summary of test. I will try to change my first design then @olivierodo .

**Comment by rezaalmanda** [comment]
This is it, have take a look @olivierodo 
![History page v2](https://github.com/restqa/restqa/assets/22217419/bc90a5bc-9084-4132-b34f-a96db8b28043)

**Comment by olivierodo** [comment]
@rezaalmanda change has been proposed and will be included in the next version 😁

![image](https://github.com/restqa/restqa/assets/4768226/903f74d6-7fa4-4679-87eb-cb7c09c3ba02)

**Comment by rezaalmanda** [comment]
Great :)
